# Napcat配置
napcat:
  base_url: "http://127.0.0.1:3032"  # 我们的WebSocket服务端地址
  token: ""                          # API Token (可选，从截图看需要配置)
  timeout: 10s                       # 请求超时时间 (高性能模式缩短)
  retry_count: 2                     # 重试次数 (减少重试提高速度)
  retry_delay: 500ms                 # 重试延迟 (缩短延迟)
  max_requests: 2000                 # 最大并发请求数 (高性能模式)
  connection_pool_size: 20           # WebSocket连接池大小 (增加连接数)
  batch_size: 200                    # 批量处理大小 (增大批次提高吞吐)
  worker_pool_size: 100              # 工作协程池大小 (增加工作线程)

# 导出配置
export:
  output_dir: "./exports"            # 导出文件保存目录
  max_file_size: 104857600          # 最大文件大小 (100MB)
  max_message_count: 10000          # 单次最大消息数量
  include_images: true              # 是否包含图片信息
  date_format: "2006-01-02 15:04:05" # 日期格式
  compression: false                # 是否压缩输出文件

# 日志配置
log:
  level: "info"                     # 日志级别: debug, info, warn, error
  format: "text"                    # 日志格式: json, text
  output: "file"                    # 输出方式: stdout, file, both
  filename: "qq-chat-exporter.log"  # 日志文件名
  max_size: 100                     # 最大文件大小 (MB)
  max_backups: 3                    # 最大备份文件数
  max_age: 30                       # 最大保存天数
  compress: true                    # 是否压缩旧日志文件