name: "Build Fix Action"
on:
  push:
  pull_request:
  workflow_dispatch:

permissions: write-all

jobs:
  Build-Fix-Framework:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./NapCatQQ-4.8.102
    steps:
    - name: Clone Main Repository
      uses: actions/checkout@v4
    - name: Use Node.js 20.X
      uses: actions/setup-node@v4
      with:
          node-version: 20.x

    - name: Build NapCat Framework Fix
      run: |
          npm i --legacy-peer-deps
          cd napcat.webui
          npm i --legacy-peer-deps
          cd ..
          npm run build:framework
          cd dist
          npm i --omit=dev --legacy-peer-deps
          cd ..
    - name: Upload Artifact
      uses: actions/upload-artifact@v4
      with:
        name: NapCat.Framework
        path: ./NapCatQQ-4.8.102/dist

  Build-Fix-Shell:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./NapCatQQ-4.8.102
    steps:
        - name: Clone Main Repository
          uses: actions/checkout@v4

        - name: Use Node.js 20.X
          uses: actions/setup-node@v4
          with:
              node-version: 20.x
          
        - name: Build NapCat Shell Fix
          run: |
                npm i --legacy-peer-deps
                cd napcat.webui
                npm i --legacy-peer-deps
                cd ..
                npm run build:shell
                cd dist
                npm i --omit=dev --legacy-peer-deps
                cd ..

        - name: Upload Artifact
          uses: actions/upload-artifact@v4
          with:
              name: NapCat.Shell
              path: ./NapCatQQ-4.8.102/dist

  release-napcat-fix:
    needs: [Build-Fix-Framework,Build-Fix-Shell]
    runs-on: ubuntu-latest
    steps:

    - name: Clone Main Repository
      uses: actions/checkout@v4

    - name: Download All Artifact
      uses: actions/download-artifact@v4
      
    - name: Compress subdirectories
      run: |
        cd ./NapCat.Shell/
        zip -q -r NapCat.Shell.zip *
        cd ..
        cd ./NapCat.Framework/
        zip -q -r NapCat.Framework.zip *
        cd ..
        rm ./NapCat.Shell.zip -rf
        rm ./NapCat.Framework.zip -rf
        mv ./NapCat.Shell/NapCat.Shell.zip ./
        mv ./NapCat.Framework/NapCat.Framework.zip ./

        mkdir ./NapCat.Framework.Windows.Once
        unzip -q ./NapCatQQ-4.8.102/external/LiteLoaderWrapper.zip -d ./NapCat.Framework.Windows.Once
        cd ./NapCat.Framework.Windows.Once
        ls 
        mkdir -p ./LL/plugins/NapCatQQ
        unzip -q ../NapCat.Framework.zip -d ./LL/plugins/NapCatQQ
        zip -q -r NapCat.Framework.Windows.Once.zip *
        cd ..
        mv ./NapCat.Framework.Windows.Once/NapCat.Framework.Windows.Once.zip ./

    - name: Generate Release Tag
      run: |
        echo "RELEASE_TAG=fix-$(date +'%Y%m%d-%H%M%S')" >> $GITHUB_ENV
        echo "RELEASE_NAME=NapCat Fix $(date +'%Y-%m-%d %H:%M:%S')" >> $GITHUB_ENV

    - name: Create GitHub Release
      uses: softprops/action-gh-release@v1
      with:
        name: ${{ env.RELEASE_NAME }}
        tag_name: ${{ env.RELEASE_TAG }}
        token: ${{ secrets.GITHUB_TOKEN }}
        body: |
          ## NapCat 语音处理修复版
          **构建信息:**
          - 构建时间: $(date +'%Y-%m-%d %H:%M:%S')
          - 提交哈希: ${{ github.sha }}
        files: |
          NapCat.Framework.zip
          NapCat.Shell.zip
          NapCat.Framework.Windows.Once.zip
        draft: false
        prerelease: false